name: covidly
description: Covid 19 tracker

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  keyboard_visibility: ^0.5.6
  fluttertoast: ^8.0.0
  shared_preferences: ^2.0.5
  http: ^0.13.3
  cached_network_image: ^2.0.0
  lottie: ^1.0.1
  percent_indicator: ^2.1.7+2
  bottom_navy_bar: ^5.6.0
  intl: ^0.17.0
  url_launcher: ^5.7.10
  fl_chart: ^0.36.2
  dots_indicator: ^2.0.0
  news_api_flutter_package: ^1.1.0
  camera: ^0.8.1+3
  tflite: ^1.1.2
  swipe_cards: ^0.1.0
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5

  sqflite:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/labels.txt
    - assets/model_unquant.tflite
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/lottie/
    - assets/images/flags/
    - assets/images/symptoms/
    - assets/images/error_images/

